### PR TITLE
Replace deprecated pkg_resources with packaging

### PR DESCRIPTION
**Pull request by oh2fih**
Replace `pkg_resources.Requirement` with `packaging.requirements.Requirement`.

- Resolves https://github.com/madpah/requirements-parser/issues/88
- Closes https://github.com/madpah/requirements-parser/pull/80 as importing `setuptools` becomes unnecessary.

### CODE REVIEW

**Comment by madpah** [comment]
Thanks for the contribution @oh2fih. As you can see - all tests are failing - looks like you forgot to commit an updated `poetry.lock` file - can you include this?

**Comment by oh2fih** [comment]
@madpah Thanks for accepting the pipeline. I did not yet really focus on the workflows so much as I could not get their output anyway. The `poetry.lock` has now been updated, and the workflow is waiting for the approval again so that I can see what else still failing.

**Comment by oh2fih** [comment]
Although the output looks the same, I still got this typing error:

```
requirements/requirement.py:249: error: Incompatible types in assignment 
(expression has type "List[List[Union[str, Any]]]", variable has type
"List[Tuple[str, str]]")  [assignment]
                req.specs = specs
                            ^
Found 1 error in 1 file (checked 1 source file)
```

Should I try to fix this or just blindly `# type: ignore` as you have done 30 times in this file already? :thinking:

**Comment by oh2fih** [comment]
Getting closer!
- ✅ It HAD to be `List[Tuple[str, strt]]` although it was complaining the opposite.
- ✅ Now all tests from `test_requirements.py` are passing.
- ❌ The `test_parser.TestParser.test_requirement_files` is failing.

**Comment by madpah** [comment]
@oh2fih - can you also see that the DCO check is not passing https://github.com/madpah/requirements-parser/pull/105/checks?check_run_id=28655859108

**Comment by oh2fih** [comment]
Yes, the practice of using `Signed-off-by` seems a bit difficult to adopt.

It seems the old library used was a bit more flexible with the line formatting and I still need to add some pre-processing. However, I am now able to run the workflows on the fork, so maybe I'll get there.

**Comment by oh2fih** [comment]
@madpah It is always a bit challenging to adjust to the developing environment of a new project, but the `tox` was actually awasome, enabling running the tests locally without manually installing all the requirements. Now I finally got all the tests to pass, and managed to use solutions that weren't too hacky, I think. :sunglasses:

**Comment by madpah** [comment]
No worries - this PR is here forever.

Thanks for the contribution @oh2fih - `0.11.0` has been released.

**Pull request merged**
